apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverse-proxy-app
  labels:
    run: reverse-proxy-app
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      run: reverse-proxy-app
  template:
    metadata:
      labels:
        run: reverse-proxy-app
    spec:
      containers:
      - name: reverse-proxy-app
        image: {{ .Values.image }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.port }}
        resources:
          limits:
            cpu: "1"
          requests:
            cpu: 300m
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 5
